#!/bin/bash

# util script for git repository operator
# It can merge a branch into master with command:
# fast-merge <branch>
# You can use `-d <dest>` to specify another target branch:
# fast-merge -d feature <branch>
# You can merge multiple branch at the same time
# fast-merge <branch-1> <branch-2> <branch-3>
# You can use `-h` to show usage:
# fast-merge -h

DEST=master

Usage () {
  echo "Usage:"
  echo 'fast-merge -d <dest-branch-name> branch-names...'
} 

Merge () {
  echo merge branch $1
  git checkout $DEST
  git pull
  git checkout $1
  git pull
  git rebase $DEST
  git checkout $DEST
  git merge $1
  git push
  echo '===== ' $1 ' merged ====='
}

GetDest() {
  while getopts "d:h" arg
  do
    case $arg in
      d)
        DEST=$OPTARG
	;;
      h)
        Usage
	;;
      ?)
        echo 'unknown argument'
	exit 1
	;;
    esac
  done
}

GetDest $@
shift "$((OPTIND - 1))"

for branch in $@
do
  Merge $branch
done
